# Generated by Django 3.2 on 2021-10-23 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('build', '0007_alter_lesson_subjects'),
        ('user', '0003_teacher_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='subjects',
        ),
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.CharField(choices=[('GRF', 'Geography'), ('CHE', 'Chemistry'), ('PHY', 'Physics'), ('MAT', 'Mathematics'), ('NAT', 'Nature'), ('ENG', 'English'), ('GEO', 'Georgian'), ('MUS', 'Music'), ('BIO', 'Biology'), ("[('GRF', 'Geography'), ('CHE', 'chemistry'), ('PHY', 'physics'), ('MAT', 'Mathematics'), ('NAT', 'Nature'), ('ENG', 'English'), ('GEO', 'Georgian'), ('MUS', 'Music'), ('BIO', 'Biology')]", 'Subject In School Choices'), ('<django.db.models.fields.CharField>', 'Name')], default=django.utils.timezone.now, max_length=248),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('GRF', 'Geography'), ('CHE', 'Chemistry'), ('PHY', 'Physics'), ('MAT', 'Mathematics'), ('NAT', 'Nature'), ('ENG', 'English'), ('GEO', 'Georgian'), ('MUS', 'Music'), ('BIO', 'Biology'), ("[('GRF', 'Geography'), ('CHE', 'chemistry'), ('PHY', 'physics'), ('MAT', 'Mathematics'), ('NAT', 'Nature'), ('ENG', 'English'), ('GEO', 'Georgian'), ('MUS', 'Music'), ('BIO', 'Biology')]", 'Subject In School Choices'), ('<django.db.models.fields.CharField>', 'Name')], max_length=248),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
