# Generated by Django 3.2 on 2021-10-23 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211023_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='men_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_meneger', to='user.teacher'),
        ),
    ]
